apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mypod
  name: mypod
spec:
  containers:
  - image: kubespy-port-demo-node
    imagePullPolicy: Never
    name: mypod
    ports:
    - containerPort: 8000
    env:
    - name: NODE_OPTIONS
      value: "--inspect=0.0.0.0:2345"
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
